"""simulate --- a module that checks that the development has been completed
and runs the Bullet Physics app to simulate a "life" of a robot.

Author: Joshua Hawthorne-Madell
"""
import os
import time
import sys
import subprocess
from pathlib import Path
from collections import namedtuple
#from simulation.python_sim.runit import run_simulation_entry

import pdb

SimulationData = namedtuple('SimulationData', ['fitness'])


def grab_data(data_file):
    """
    Returns a list of data that was generated by the simulation
    """
    with open(data_file, 'r') as fr:
        lines = [line.strip('\n') for line in fr]
        return SimulationData(*lines)


def run_simulation(io_file, sim_num, test=False, grav=-9.81):
    """
    Returns fitness after running the simulation.
    """
    base_dir = os.path.dirname(os.path.abspath(__file__))
    runit_script = os.path.join(base_dir, '../simulation/python_sim/runit.py')
    
    data_file = os.path.join(os.path.abspath(io_file), f'sim_{sim_num}.dat')
    check_file = check_file = os.path.join(os.path.abspath(io_file), f'buffer_{sim_num}.dat')

    # safety timeout 1
    start_time = time.time()
    while not os.path.isfile(check_file):
        time.sleep(0.1)
        if time.time() - start_time > 30:
            print(f"ERROR: Timed out waiting for buffer file: {check_file}")
            return 0.0  

    # run in headless mode to avoid GLUT graphics conflicts in multiprocessing (for now)
    try:
        subprocess.call([
                sys.executable, runit_script,
                '-f', os.path.abspath(io_file), # absolute path to try and get it pointing towards the /io folder
                '-n', str(sim_num),
                '-g', str(grav),
                '--headless'
            ], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=60) # 60 sec simulation timeout safeguard
    except subprocess.TimeoutExpired:
        print(f"ERROR: Simulation {sim_num} hung and was forcefully terminated.")
        return 0.0
        
    # safety timeout 2
    start_time = time.time()
    while not os.path.isfile(data_file):
        time.sleep(0.1)
        if time.time() - start_time > 10:
            print(f"ERROR: Timed out waiting for simulation data output: {data_file}")
            return 0.0

    data = grab_data(data_file)
    fitness = float(data.fitness)

    try:
        if os.path.isfile(check_file): os.remove(check_file)
        if os.path.isfile(data_file): os.remove(data_file)
    except OSError:
        pass # ignore if another process deleted it concurrently

    return fitness

'''
def run_simulation_graphics(io_file, sim_num, test=False, grav=-9.81):
    """
    Runs the simulation with GLUT-enabled graphics. Pretty much identical to 
    run_simulation() in this file, but without the storage components (data_file)
    and without the headless command
    """
    base_dir = os.path.dirname(os.path.abspath(__file__))
    runit_script = os.path.join(base_dir, '../simulation/python_sim/runit.py')
    
    check_file = io_file + 'buffer_' + str(sim_num) + '.dat'

    # build command to run the simulation
    while not os.path.isfile(check_file):
        time.sleep(0.1)

    # run the simulation once using GLUT-based graphics
    run_simulation_entry(
        os.path.abspath(io_file),
        sim_num,
        grav,
        False
    )

    os.remove(check_file)

    return 0
'''